### ISSUE TITLE
[Documentation] Usage of Jetty vs. Tomcat

### ISSUE THREAD

**Issue by fleimgruber** [geonetwork/docker-geonetwork#115]
As a user I want to use Tomcat instead of Jetty in the Docker container, but could not find related information in https://github.com/geonetwork/docker-geonetwork/tree/main/4.4.1.

**Comment by juanluisrp** [comment]
@fleimgruber this is the repository of the Docker official image of GeoNetwork. It is based on Jetty.
If you want to use Tomcat you would need to implement something like in the 3.12.x series of GN:
https://github.com/geonetwork/docker-geonetwork/blob/bef3f1c871c962fbb3bbfac834e0e0d72772162b/3.12.9/Dockerfile#L1-L32

I guess this should mostly work just changing the `GN_VERSION` and `GN_DOWNLOAD_MD5` and using a Tomcat with Java 11 as base image.
