### ISSUE TITLE
H2 database lost when container is destroyed

### ISSUE THREAD

**Issue by juanluisrp** [geonetwork/docker-geonetwork#12]
Since `gn.h2.db` is created in `/usr/local/tomcat/webapps` it is lost every time the container is destroyed. 

A workaround is to mount `/usr/local/tomcat/webapps/gh.h2.db` as a volume, but the preferred method would be to store the database in the `DATA_DIR` or in another place specified by an environment variable.

**Comment by brechtvm** [comment]
> A workaround is to mount /usr/local/tomcat/webapps/**gn**.h2.db as a volume, but the preferred method would be to store the database in the DATA_DIR or in another place specified by an environment variable.

Typo I assume in your post @juanluisrp ; gh.h2.db needs to be gn.h2.db

**Comment by adonm** [comment]
A bit cleaner workaround is set the location using the GEONETWORK_DB_NAME env var, e.g. we have ours set to default DATA_DIR location like so:

`GEONETWORK_DB_NAME=/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/geonetwork_db` results in a db created at `/usr/local/tomcat/webapps/geonetwork/WEB-INF/data/geonetwork_db.h2.db`

**Comment by adonm** [comment]
Note the documentation related to this has been updated on https://hub.docker.com/_/geonetwork/ so this issue could probably be closed @juanluisrp
