### ISSUE TITLE
Release of GN v3.6.0

### ISSUE THREAD

**Issue by juanluisrp** [geonetwork/docker-geonetwork#15]
GN v3.6.0 has been released. 

Actions: Prepare the new Docker image.

**Comment by gannebamm** [comment]
see my pull request #16

**Comment by gannebamm** [comment]
@juanluisrp @doublebyte1 Should be solved?

**Comment by juanluisrp** [comment]
I will try your PR today and check if it is working fine today. Then I will send Docker library a PR for the new release.

**Comment by doublebyte1** [comment]
I already did a [PR](https://github.com/docker-library/official-images/pull/5347) here.

**Comment by doublebyte1** [comment]
> @juanluisrp @doublebyte1 Should be solved?

Yes, I think so.
