### ISSUE TITLE
MaxUploadSizeExceededException on files big files

### ISSUE THREAD

**Issue by uamoreno** [geonetwork/docker-geonetwork#18]
Hello, we are using version 3.2.2, but we can not make geonetwork to upload files bigger than 100MB, after looking around we found a file: /usr/local/tomcat/webapps/geonetwork/WEB-INF/config-spring-geonetwork.xml where a code fragment must be placed attending some forums advices, but nothing happens:

```
<bean id="multipartResolver"
        class="org.springframework.web.multipart.commons.CommonsMultipartResolver">
    <property name="maxUploadSize" value="1000000000"/>
<!-- set to 1GB -->
</bean>

```

After copying the new file we have restarted de container several times but the exceptions keeps rising on files greater than 100MB.

What others files must be changed or what docker configuration must be set in way to upload big files?

**Comment by doublebyte1** [comment]
@uamoreno this seems like a GN configuration problem, not a docker issue. You are very welcome to post your question at the [Geonetwork Users Mailing List](https://sourceforge.net/projects/geonetwork/lists/geonetwork-users).
