### ISSUE TITLE
error when I used the docker geonetwork:postgres with docker compose v3

### ISSUE THREAD

**Issue by rgillain-cirb** [geonetwork/docker-geonetwork#19]
I have try to use the docker geonetwork:postgres with docker compose v3.

In my docker compose I have 2 service: one for my postgres database and one for my geonetwork.
I use depends_on and a command to verifiy that the database is working.

The command that I have use for that is 
command: sh -c '/usr/bin/wait-for-it.sh myPostgresDocker:5432 -t 60 -- catalina.sh run'
When I used that command I see that the content of the Entrypoint is never executed, so the configuration for the database is never done. (the file jdbc.properties don't have properties like "jdbc.username")

For information , the script "wait-for-it.sh" is comming from  that url "https://github.com/vishnubob/wait-for-it".

I don't know If I need to use another method to validate that my db is available or if a change have to be done to be able to use the docker compose v3 and to validate that a database is available before the configuration of the database.

For now I have change the command like that to solve the problem : 
"sh -c '/usr/bin/wait-for-it.sh myPostgresDocker:5432 -t 60 -- /entrypoint.sh catalina.sh run'".

**Comment by juanluisrp** [comment]
`depends_on` only sets the order in which the containers will be started but that doesn't mean that the database will be ready when GeoNetwork container is started.  [`docker-compose` documentation](https://docs.docker.com/compose/startup-order/) suggest some approaches to this problem, one of then is using a tool like `wait-for-it` as you suggested above.
