### ISSUE TITLE
Where are the schema plugins?

### ISSUE THREAD

**Issue by icemagno** [geonetwork/docker-geonetwork#25]
There is no schema plugins and I have no idea how to add a new one from https://github.com/metadata101/iso19139.mcp

**Comment by pvgenuchten** [comment]
Hi @icemagno, a challenge with many schema plugins is that they need to be build as part of the sources. However there are some that can be copied in as a zip file. I use this approach [here](https://github.com/geonetwork/docker-geonetwork/blob/27a30d076d7358917d9f0d06577ff856f2e8e2b6/3.8.0/postgres/docker-entrypoint.sh#L40).

In previous times the Web UI of GeoNetwork had a capabilitiy to load plugins, but it was not used much and was deprecated.

For those schema plugins that don't need rebuilding theoretically we could add environment parameter that will load the plugin from github and deploy it as part of the installation.

**Comment by juanluisrp** [comment]
Also you can pass Docker an environment variable named `geonetwork.schema.dir` pointing to the folder where you want the schema plugins. For example you could mount an external directory and put your schemas there running something like:
```
docker run --name gn \
    -v /host/path/to/schema_plugins:/var/schema_plugins \
    -e "geonetwork.schema.dir=/var/schema_plugins" \
    -p 8080:8080 \
    geonetwork:latest
```

Check [GeoNetwork's docs](https://geonetwork-opensource.org/manuals/3.8.x/ca/maintainer-guide/installing/customizing-data-directory.html#advanced-data-directory-configuration) about setting a custom data directory.
