### ISSUE TITLE
db-type as environment variable

### ISSUE THREAD

**Issue by pvgenuchten** [geonetwork/docker-geonetwork#29]
now is hardcoded an image for use with postgres, maybe we can use an image where dbtype is a parameter, people can decide to use mysql, sqlserver, oracle or postgres
off course we have a challenge to download dynamically latest db driver (or include all?)

h2 could be the default value for dbtype, in that case we would only have a single docker image to maintain

**Comment by juanluisrp** [comment]
You can pass now `GEONETWORK_DB_TYPE` environment variable. For example:
```bash
docker run -p 8080:8080 -e GEONETWORK_DB_TYPE=postgres geonetwork:4
```
