### ISSUE TITLE
Attach thumbnails - relative path?  

### ISSUE THREAD

**Issue by KoalaGeo** [geonetwork/docker-geonetwork#37]
Hi, 

I've followed the install documentation to persist data, and wanted to use graphicOverview in my catalog. 

DATA_DIR=/var/lib/geonetwork_data -v /host/geonetwork-docker:/var/lib/geonetwork_data 

I've copied thumbnail images to - /host/geonetwork-docker/data/Thumbnails/Geo_125k/XXXXX.jpg

And edited the record to the below which I thought would pick up the file but it's not working. 

<gmd:graphicOverview>
            <gmd:MD_BrowseGraphic>
               <gmd:fileName>
                  <gco:CharacterString>/var/lib/geonetwork_data/data/Thumbnails/Geo_125k/XXXXX.jpg</gco:CharacterString>
               </gmd:fileName>
               <gmd:fileDescription>
                  <gco:CharacterString>Thumbnail</gco:CharacterString>
               </gmd:fileDescription>
            </gmd:MD_BrowseGraphic>
         </gmd:graphicOverview>

Am I misunderstanding how to use relative paths between docker and host volumes?

**Comment by KoalaGeo** [comment]
I've also tried using /host/geonetwork-docker/data/Thumbnails/Geo_125k/XXXXX.jpg in the xml file.

**Comment by nmtoken** [comment]
Nothing to do with docker, but If your data_dir is `var/lib/geonetwork_data`  and your  file is  in `/var/lib/geonetwork_data/data/Thumbnails/Geo_125k/XXXXX.jpg` the relative path to the image should be `data/Thumbnails/Geo_125k/XXXXX.jpg`



data/Thumbnails/Geo_125k/XXXXX.jpg

**Comment by KoalaGeo** [comment]
Data directory on the host is `/host/geonetwork-docker` which is a volume added to the container at `/var/lib/geonetwork_data`. I thought that meant if I put files in `/host/geonetwork-docker/data/Thumbnails/Geo_125k/XXXXX.jpg` then the path inside the container would be `/var/lib/geonetwork_data/data/Thumbnails/Geo_125k/XXXXX.jpg`. 

I've tried as you suggest and no luck. 

For an image I added manually the path GeoNetwork created is `http://10.121.22.252:8080/geonetwork/srv/api/records/a2677cf6-c446-4dbc-882c-c3ac8909c3c5/attachments/Evolution_of_the_Rangwa_Complex_And_Kisingiri_Volcano_Thumb.png?approved=true` which doesn't appear to be anything to do with the mounted volume....

**Comment by KoalaGeo** [comment]
Problem solved! 

Should be `http://gdcs1.gdc.com/Metadata/Thumbnails/Geo_125k/XXXXX.jpg`
