### ISSUE TITLE
container immediately exits

### ISSUE THREAD

**Issue by d3netxer** [geonetwork/docker-geonetwork#82]
When I try to run a container using this command as listed in the documentation (https://hub.docker.com/_/geonetwork):

```
$ docker run --name some-geonetwork -d -p 8080:8080 geonetwork
```

The container immediately exists. Isn't it supposed to stay up?

**Comment by d3netxer** [comment]
Is it possible that GeoNetwork requires an Elasticsearch instance?

when I try to look at the logs, this is the output:
```
$ docker logs some-geonetwork
********************************************************************
WARNING: Environment variable ES_HOST is mandatory

GeoNetwork requires an Elasticsearch instance to store the index.
Please define the variable ES_HOST with the Elasticsearch 
host name. For example

docker run -e ES_HOST=elasticsearch geonetwork:4.0.5

********************************************************************
```

I do not see anything about Elasticsearch in the documentation

**Comment by juanluisrp** [comment]
GN requires ES in versions >= 4. Previous versions don't.


You can find some samples of `docker-compose` configuration files here:
https://github.com/geonetwork/docker-geonetwork/blob/main/4.0.5/docker-compose.yml
